### ISSUE TITLE
/get_working_hoursコマンドの不具合

### ISSUE THREAD

**Issue by L3tsG0** [NSL-Admin/ra-timecard-recorder#12]
## 問題
2024年1月8日現在，`get_working_hours 2024/01`とすると稼働時間が表示されない．
また今月の稼働時間を問い合わせているのにも関わらず’’今月’’ではなく’’2024年1月’’と表示される．
![実際の様子](https://github.com/NSL-Admin/ra-timecard-recorder/assets/132372519/e1e4d79d-e9e2-4eb6-a6d7-35f18cc311ff)

## 考えられる要因

- RA名を新しく登録した後の初めての勤務の後に問い合わせたので，そこが原因な可能性がある．

**Comment by t0d4** [comment]
↑は勤務報告を2023年として報告していたことが原因だったが，どうやら勤務時間が一切存在しないときにも `else` 側に行かず，"N月の勤務時間はありません"と出ない場合があるようなので要確認．
https://github.com/NSL-Admin/ra-timecard-recorder/blob/29fe5f34896b8c7655f0ff1a50588abfcd110dad/app.py#L429-L434

**Comment by t0d4** [comment]
これは以下のif文に渡すobjectが問題だった．`working_hours_of_all_RAs` は `sqlalchemy.engine.result.ChunkedIteratorResult` オブジェクトなので，これは仮にResultが0件だったとしてもIf文で`False`と評価されない．よって，当該if文が無条件でTrue側に分岐するようになってしまっていた．`if working_hours_of_all_RAs.all():`としてiteratorをlistにcollectしてから判定することで解決．

https://github.com/NSL-Admin/ra-timecard-recorder/blob/a01f7571e1ef5b69a7538a6633d7c3d808196eef/app/listeners/commands/get_working_hours.py#L40-L57

**Comment by t0d4** [comment]
先ほどのプルリクエストでは最初に`.all()`を呼んでしまっていたため，[ドキュメント](https://docs.sqlalchemy.org/en/20/core/connections.html#sqlalchemy.engine.IteratorResult:~:text=_TP%5D%5D-,Return%20all%20rows%20in%20a%20sequence.,result%20set%20after%20invocation.%20Subsequent%20invocations%20will%20return%20an%20empty%20sequence.,-New%20in%20version)によればこの時点で全ての結果がconsumeされ，以降のfor文のときにはすでにResultが空になっていた．
https://github.com/NSL-Admin/ra-timecard-recorder/blob/8a0ebb0a981bd54407845b64c1331fde0e64f122/app/listeners/commands/get_working_hours.py#L55-L59

最初から`.all()`で取得し，以降はそのリストを使用するようにして修正．

**Comment by t0d4** [comment]
#22 で解決
