### ISSUE TITLE
/get_working_hoursの時間に休憩時間が含まれる問題

### ISSUE THREAD

**Issue by L3tsG0** [NSL-Admin/ra-timecard-recorder#19]
`/get_working_hours`の勤務時間に休憩時間が含まれてしまっている

例)1月の勤務が以下のみの場合．
2024/1/1
勤務 11:00-14:00
休憩 12:00-13:00

総勤務時間が3hとして返ってくる

**Comment by t0d4** [comment]
コードの下に示した部分で，`sqlfuncs.sum(TimeCard.duration)`を`sqlfuncs.sum(TimeCard.duration) - sqlfuncs.sum(TimeCard.break_duration)`に変更すれば直りそうな気がするが，`sqlfuncs.sum()`の結果同士は四則演算可能なのかをDocsで確かめる必要がある．

また，ユーザへのメッセージは「稼働時間」より「実働時間」などの方が分かりやすいかもしれない．
https://github.com/NSL-Admin/ra-timecard-recorder/blob/c6674da622aff834d33c87c2c51d1406f92a8841/app/listeners/commands/get_working_hours.py#L42-L53

**Comment by t0d4** [comment]
`sqlfuncs.sum(TimeCard.duration)`を`sqlfuncs.sum(TimeCard.duration - TimeCard.break_duration)`に変更すれば正しく動くことを確認した．

**Comment by t0d4** [comment]
#25 にて修正済．
